---
- ansible.builtin.stat:
    path: /usr/local/bin/consul-template
  register: consul_template

- ansible.builtin.debug:
    msg: The files exist
  when: not consul_template.stat.exists

# TODO: Check consul template version

- name: Include consul-template installation
  ansible.builtin.import_tasks: install.yml
  # when: not consul_template.stat.exists

- debug:
    msg: "{{ hostvars[item].app_domain }}"
  with_items: "{{ groups['webservers'] }}"

- name: sites
  ansible.builtin.template:
    src: load-balancer.conf.ctmpl.j2
    dest: /etc/nginx/conf.d/{{ item }}.conf.ctmpl
  with_items: "{{ groups['webservers'] }}"

- name: generate consul template config
  ansible.builtin.template:
    src: config.hcl.j2
    dest: /etc/consul-template.d/config.hcl

- name: restart to consul template service
  ansible.builtin.service:
    name: consul-template
    state: restarted

# Check multiple file is exists
#
# - stat:
#     path: "{{ item }}"
#   register: file_details
#   loop:
#     - info.text
#     - info.html
#
# - debug:
#     msg: The files exist
#   when: file_details.results|map(attribute='stat.exists') is all
