---

- name: Install message for PostreSQLDB
  ansible.builtin.debug:
    msg: Installing PostreSQL DB Server

- name: apt update
  ansible.builtin.apt:
    update_cache: yes

- name: install wget 
  ansible.builtin.apt:
    name: wget
    state: present

- name: install curl 
  ansible.builtin.apt:
    name: curl
    state: present

- name: install ca-certificates
  ansible.builtin.apt:
    name: ca-certificates
    state: present


- name : insert key 
  ansible.builtin.apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name : add repo
  ansible.builtin.apt_repository:
    repo: deb  http://apt.postgresql.org/pub/repos/apt/ focal-pgdg main
    state: present
    filename: postresql

